### ISSUE TITLE
I cant find “extensions”

### ISSUE THREAD

**Issue by 1percentAndrew** [Alphalaneous/DeathLink-Geode#6]
Me and my friend have been wanting to play this for a while now but I can’t find the file “extensions”. And i tried to look for a tutorial but couldn’t find one. (Sorry alpha i tried adding you on discord for this) Could this be happening because geode and geometry dash are on different drives? I just want to get this working, if any of you guys can help that would be great!

**Comment by Alphalaneous** [comment]
Extensions is a 2.1 thing. We use geode now. To add, DeathLink is part of the Globed geode mod now

**Comment by 1percentAndrew** [comment]
Yeah I found that out, sorry for bugging you guys.
